using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using MVC_Assignment4.Models;

namespace MVC_Assignment4.DAL
{
	public class Initializer : System.Data.Entity.DropCreateDatabaseIfModelChanges<AlbumContext>
	{
		protected override void Seed(AlbumContext context)
		{
			var albums = new List<Album>
			{
				new Album { Artist="The Pretty Reckless", Title = "Light Me Up", ReleaseDate = DateTime.Parse("2010-06-22"), ArtistBio = @"For two years singer, rhythm guitarist and Gossip Girl actress Taylor Momsen worked with several producers before meeting Kato Khandwala.[4] Momsen has said that she liked Khandwala because he was a rock producer as opposed to a pop producer.[4] Khandwala introduced Momsen to Ben Phillips[5] and the three of them began to write songs together. Three unnamed musicians were hired to form the band with Momsen.[6] The band were originally called The Reckless, but had to change the name due to trademark problems.[7] The band played its first concert on May 5, 2009 at The Annex in New York.[6][8][9] After seven concerts the lineup of the band was changed.[6] The new lineup of the band consisted of Momsen with John Secolo (guitar), Matt Chiarelli (bass) and Nick Carbone (drums).[1] The second line-up of the band also played its first concert at The Annex on June 3, 2009.[6] They recorded some demos in early 2009 and they opened for The Veronicas on their North American tour.[1] In 2010, Secolo, Chiarelli and Carbone left the band. At present, Momsen is the singer and rhythm guitarist, with Ben Phillips on lead guitar, Mark Damon on bass, and Jamie Perkins on drums, all of whom played in the band Famous in the early 2000s.[1][10] Momsen stated in an interview with OK! Magazine that the band signed with Interscope Records and would be releasing their debut album in 2010.[11] In an interview with QTV, Momsen reported the influences on the band to include The Beatlesand Oasis, along with grunge band Nirvana. She also stated that her personal influences include Kurt Cobain and Joan Jett.[12] After the band announced they had signed to Interscope Records, two new recordings of demo songs (""He Loves You"" and ""Zombie"") were posted on their Myspace.[13]On December 30, 2009, the band released a new promo song entitled ""Make Me Wanna Die"". The song was offered as a limited-time free download for fans on their Interscope Records website.[14] The band launched ""Make Me Wanna Die"" on the soundtrack and it appeared in the end credits of the 2010 film Kick - Ass.[1] The song was the band's first single, and was released on May 17, 2010, with the debut album set to be released in August.[10] On April 9, 2010, they performed during the ""Vans Warped Tour 2010 Kick-Off Party"" and performed at The Bamboozle music festival on May 1, 2010. They played the entire Warped Tour 2010.[15]
							Momsen on the Light Me Up Tour in April 2011
							Their first EP was released on June 22, 2010, with mixed reactions.Rolling Stonemagazine classified the sound as ""generic"".[16] It contained four songs, three of which can be found on their debut album: ""Make Me Wanna Die"", ""My Medicine"", and ""Goin' Down"".The first single ""Make Me Wanna Die"" was released on May 17, 2010.A viral video was released to promote the single.The full record was released on August 31, 2010.
							The song ""Miss Nothing"" was the second single to be released from Light Me Up, on August 9, 2010.It was aired exclusively on the British radio station, BBC Radio 1, on July 22, 2010.The band introduced it as their next UK single after a show on theWarped Tour.[17] A video for ""Miss Nothing"" was released on July 20 on Vevo.The US release of Light Me Up was delayed, not being released until February 2011.The first single released in the US officially was Just Tonight, which was the third single released in Australia and United Kingdom among other countries.
							Momsen in July 2011 The Evanescence Tour was the third worldwide concert tour by American rock bandEvanescence which their performances were supported by The Pretty Reckless.Lead singerTaylor Momsen stated she was a ""big fan of Evanescence, so it''s really exciting to be opening for them"".[18] The band opened for Evanescence at the historic Hollywood Palladium in Los Angeles.Amy Lee told MTV about Momsen: ""She's got a great voice; she's real sweet,"" and laughingly said that being one of Momsen's first concerts makes her feel ""old, but very, very flattered.""Guns N' Roses' Chinese Democracy Tour confirmed The Pretty Reckless as opening act in the following tour dates in November 2012 [19]
							2012 saw the release of two singles from the album, ""You"" and ""My Medicine"".Videos for both singles were released - ""You"" featuring Momsen in a small empty apartment playing the guitar, and ""My Medicine"" featuring Momsen at an out of control party as she sings about being under the influence of alcohol and drugs.Later 2012 she appeared in a video completely naked.In the video entitled ""The Words - Under The Water,"" Taylor appeared in a black - and - white film while saying the lyrics like reciting a poem. By the time the video ends, Taylor appears without her clothes on and her private parts blurred.[20]" },
				new Album { Artist="Pierce the Veil", Title="Selfish Machines", ReleaseDate=DateTime.Parse("2010-06-21"), ArtistBio= @"During August 2009, Pierce the Veil announced that they were currently in studio recording new material for their next album. After a few months off the road and building anticipation for their sophomore release, the band moved to Los Angeles to record their album Selfish Machines with Producer Mike Green. Singer and lyricist Vic Fuentes stated, ""The title refers to human nature and the animal-like qualities inside all of us that we try and hide, but should just learn to accept.We are all selfish machines and we all have natural tendencies to want, love, and take."" Selfish Machines was released on June 21, 2010 under Equal Vision Records and made it to No. 1 on the Billboard Heatseekers Chart. In support of the release, the band played a number of festivals including Bamboozle Left, South by Southwest, Never Say Never Festival, and the Vans Warped Tour. The band also contributed a cover of Blue Öyster Cult's classic song ""(Don't Fear) The Reaper"" to the Punk Goes Classic Rock compilation, released on April 27, 2010. They were a part of the Take Action Tour with Attack Attack! that went to New Zealand and Australia, and also played on the Versus Tour in Japan with Confide. They played the ""This Is a Family Tour"" with Emmure, In Fear and Faith, Of Mice & Men, and Attack Attack!, which lasted until late December 2010.
							Pierce the Veil also played at the Fox Theater in Pomona as a surprise appearance as part of the Alternative Press Tour 2010 with bands such as August Burns Red, Bring Me the Horizon, Polar Bear Club, Emarosa, and This Is Hell.On November 1, 2010, the band announced that they will be kicking off 2011 touring with Silverstein, Miss May I, The Chariot, and A Bullet for Pretty Boy on the ""Winterizer Tour"".Throughout March and April, ""The Gamechanger's Tour"" with A Day to Remember, Bring Me the Horizon, and label mates We Came as Romans followed.They also co - headlined the second leg of Escape the Fate's headlining tour ""The Dead Masquerade"". After taking the summer off to spend some more time on writing new material, the band was supposed to head out on their first ever South American Tour supporting Sum 41 in September; however, due to illness of Sum 41's frontman, the tour was cancelled.They finished up the year touring Europe with blessthefall and co - headlined the No Guts No Glory Tour with Miss May I afterwards.They once again contributed to an ""Punk goes..."" album, Punk Goes Pop 4, covering the song ""Just the Way You Are"" by Bruno Mars, which was released on November 21, 2011."},
				new Album { Artist="Pierce the Veil", Title="Collide with the Sky", ReleaseDate=DateTime.Parse("2012-07-17"), ArtistBio=@"On August 23, 2011, Pierce the Veil signed with Fearless Records. On December 22, 2011, a video update revealed in that in early 2012, the band will be going into the studio to record their 3rd studio album. On December 26, 2011, Vic Fuentes announced on the band's Facebook page that the band is finishing up writing the songs for their third album, which they began writing during the summer and while on tour with Miss May I, Woe Is Me, The Amity Affliction and letlive during November–December, and that now they'll be picking a producer to work with them on the album in early 2012.[7] On February 27, 2012, The band issued an update on their official Facebook page stating that they have chosen to work with producers Dan Korneff and Kato Khandwala at the House of Loud in New Jersey, on their upcoming third album.[8] On April 20, 2012, it was announced that the new album would be titled Collide with the Sky and would be released through Fearless Records on July 17, 2012.[9][10] On May 17, 2012, the album cover as well as the tracklist of the new album were revealed, together with the announcement of the band's first ever UK headlining tour in September 2012.[11][12] The first single from the new album, King for a Day, features Kellin Quinn of Sleeping with Sirens and was released on June 5, 2012, followed by the second single, Bulls in the Bronx, three weeks later on June 26, 2012.
							In order to promote the album, the band appeared on the Vans Warped Tour from June, 16 to August 5, 2012, playing the event's main stage for the first time. They were regularly joined on stage by Kellin Quinn to perform King for a Day together. After Warped, Pierce the Veil embarked on their first headlining tour in the UK, selling out almost all of the dates. Their following headlining tour in the US, The Collide With The Sky tour, saw a similar success. They ended the year appearing at #33 in Rock Sound magazine's best albums of 2012 list[13] as well as winning nine categories in the best of 2012 reader's poll conducted by Alternative Press, including Best Live Band of the Year, Album of the Year and Artist of the Year.[14] On January 9, 2013 Vic Fuentes released information that he had recently been in the studio writing new songs with Tom Denney.[15][16]
							On January 7, 2013, Pierce the Veil and pop-punk band All Time Low announced that they would be co-headlining the Spring Fever Tour that spring. Both bands toured across the United States, along with opening acts Mayday Parade and You Me At Six. The tour began on April 11, 2013 and ended on May 12, 2013.[17] Toward the end of the tour, on May 7, 2013, the music video for Pierce the Veil's song ""Bulls in the Bronx"" was released.[18]"},
				new Album { Artist="Bring Me the Horizon", Title="Sempiternal", ReleaseDate=DateTime.Parse("2013-04-29"), ArtistBio=@"After the intense touring schedule, Bring Me the Horizon finally completed the promotion of their third album at the end of 2011. They returned to the UK for an extended break and eventually starting work on their next album.[48] Much like their previous two albums, they wrote their fourth album in seclusion and isolation in order to stay focused. This time, they retreated to a house in the Lake District. In July, the band started to publish images of themselves recording at a 'Top Secret Studio Location,'[49] and it was revealed that they are working with producer Terry Date for the recording and the production of the album.[50] On July 30, the band announced they had left their label and signed with RCA, through which their fourth album would be released in 2013.[51] Bring Me The Horizon only played three shows in all of 2012: Warped Tour 2012 on 10 November at the Alexandra Palace in London, which they headlined and was initially believed to be their only show[52] the BBC Radio 1's Radio 1 Rocks show on 22 October, where they played a six song set supporting Bullet For My Valentine[53][54] and at a warm up show for Warped Tour in Sheffield the day before on 9 November.[55] In late October it was announced that the fourth album will be called Sempiternal and it would be released tentatively in early 2013.[56] On 22 November the band released the Draper collaborative album The Chill Out Sessions for free.[57]
							On 4 January 2013, Bring Me the Horizon released the first single from Sempiternal, ""Shadow Moses"". The song was first played by radio presenter Daniel P. Carter on Radio 1. Due to popular demand, Epitaph was forced to release the music video for the song a week earlier.[58] In January, the band also saw a change in their line up. This started early in the month when Jordan Fish, Worship keyboardist and session musician to the band during the writing of Sempiternal, was announced as a full member. Then later on in the month, Jona Weinhofen left the band.[59] Despite denied speculation that Fish replaced Weinhofen[59] reviewers have said that replacing a guitarist with a keyboardist fit their style more.[60]
							Lead vocalist Oliver Sykes at Southside Festival in Germany in 2014 The band was confirmed for several festival appearances in February with the Australian Soundwave festival, performing at all five dates in: Brisbane, Sydney, Melbourne, Adelaide and Perth,[61] then at RAMFest in South Africa with Rise Against in March,[62][63] Rock Am Ring and Rock im Park festivals in Germany in June[64] and from June till August they are playing Warped Tour 2013 in the U.S.and Canada.[65] To coincide with the 29 April release of Sempiternal the band have planned their first headline tour of the United Kingdom in 18 months with Crossfaith and Empress AD.[66]
							In support of Sempiternal, the band toured Australia with Of Mice & Men and Crossfaith,[67] a British tour with Pierce The Veil and Sights & Sounds.[68] They then completed a North American ""American Dream Tour"".The American Dream Tour had featured support from Of Mice &Men, Issues, letlive.and Northlane.[69] The band was announced as the main supporter for American band A Day to Remember on their Parks & Devastation Tour across America throughout September and October, along with support acts Motionless in White and Chiodos.[70] The band performed at Wembley Arena in London on 5 December with support acts Young Guns, Issues and Sleepwave,[71] which was recorded and released as a live album / DVD.
							Later in 2014, the band released two new tracks titled ""Drown"" on 21 October, as a stand - alone single, and ""Don't Look Down"" on 29 October, as part of the re - score of Drive."}
			};
			albums.ForEach(a => context.Album.Add(a));
			context.SaveChanges();
		}
	}
}